FROM node:14-alpine AS build
 
ENV DATABASE_URL=postgres://postgres:postgres@db:5432/onestop
WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY prisma ./prisma/

RUN yarn install 
RUN yarn prisma generate
RUN yarn prisma migrate dev --name init

COPY . .

RUN yarn build

FROM node:14-alpine AS production

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
RUN yarn install --production --frozen-lockfile

COPY --from=build /app/dist ./dist


EXPOSE 4000
CMD ["node", "dist/index.js"]

