FROM node:18 as builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install --frozen-lockfile
# Bundle app source
COPY . .

RUN npm run build

# Final image
FROM node:18

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/dist/ ./dist/

copy .env.example .

RUN yarn install --frozen-lockfile --production

CMD npm run prod

