version: '3.8'
services:
  db:
    image: postgres
    restart: always
    hostname: db
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: onestop
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/onestop


volumes:
  postgres-data:
